GET http://localhost:8001/authorization

###

GET http://localhost:8001/books
Content-Type: application/xml
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU0NDEwNjAsInVzZXJuYW1lIjoiIiwicGFzc3dvcmQiOiIifQ.yUMpX_KvYto4xaw4rARZ8kuV_UNIxE6z5uyUeT1Zyr8

###

GET http://localhost:8001/books/1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU0NDEwNjAsInVzZXJuYW1lIjoiIiwicGFzc3dvcmQiOiIifQ.yUMpX_KvYto4xaw4rARZ8kuV_UNIxE6z5uyUeT1Zyr8

###

POST http://localhost:8001/books/ HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODU0NDEwNjAsInVzZXJuYW1lIjoiIiwicGFzc3dvcmQiOiIifQ.yUMpX_KvYto4xaw4rARZ8kuV_UNIxE6z5uyUeT1Zyr8
content-type: application/json

{
    "id": "3",
    "isbn": "666555",
    "title": "Book 666",
    "author": {
      "firstname": "Brad",
      "lastname": "Jones"
    }
}
